#!/usr/bin/bash
mkdir include
mkdir src
touch src/main.c

cat << 'EOF' > src/main.c
#include <stdio.h>

int main() {

	printf("Hello, World!\n");
	return 0;
}
EOF

touch makefile

cat << 'EOF' > makefile
TARGET = main
SRC_DIR = src
OBJ_DIR = obj
BIN_DIR = bin

CC = gcc
CFLAGS = -Iinclude -Wall -Wextra -g
LDFLAGS = -fsanitize=address -fsanitize=leak
# CFLAGS = -Iinclude -Wall -Wextra -O2

SRCS = $(wildcard $(SRC_DIR)/*.c)
OBJS = $(patsubst $(SRC_DIR)/%.c, $(OBJ_DIR)/%.o, $(SRCS))

all: $(BIN_DIR)/$(TARGET)

$(BIN_DIR)/$(TARGET): $(OBJS) | $(BIN_DIR)
	$(CC) $(LDFLAGS) $(OBJS) -o $@
	@echo "Build complete: $@"

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@
	@echo "Compiled $<"

$(OBJ_DIR) $(BIN_DIR):
	mkdir -p $@

clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)
	@echo "Cleaned up build files."

run: all
	@echo "Running program..."
	@./$(BIN_DIR)/$(TARGET)
EOF

git init
touch .gitignore

cat << 'EOF' > .gitignore
bin/
obj/
.cache/
compile_commands.json

EOF

bear -- make
